#### Numpy Arrays
- NumPy arrays offer powerful library for numerical computing in Python. 
- Homogeneous Data Type: NumPy arrays contain elements that are all of the same type.
- Multidimensional: Arrays can have multiple dimensions
- Slicing and Indexing: Advanced slicing and indexing features 
- Efficient Memory Usage: NumPy arrays have a fixed size at creation.
- NumPy arrays are a foundational tool for scientific computing in Python.

In [3]:
# Import numpy library
import numpy as np

In [1]:
 #dir(np)

In [49]:
# Create 1D numpy array 
x = np.array([45,67,57,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 57 60]
<class 'numpy.ndarray'>
int32


In [51]:
# Verify the data type in array
x = np.array([45,67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

[45.  67.  57.   9.8]
<class 'numpy.ndarray'>
float64


In [53]:
# Verify the data type
x = np.array(["A",67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [55]:
# Create a 2D array
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


#### 1D arrays

In [7]:
a = np.array([10,20,30,40])
print(a)
print(type(a))

[10 20 30 40]
<class 'numpy.ndarray'>


In [8]:
print(a.shape)
print(a.size)
print(a.dtype)

(4,)
4
int32


In [13]:
# Reshapig an array using reshape()
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [10]:
print(b.ndim)
print(b.shape)
print(b.size)

2
(2, 2)
4


In [57]:
# Create an array with arange()
c = np.arange(3,10)
print(c)
type(c)

[3 4 5 6 7 8 9]


numpy.ndarray

In [14]:
print(c.ndim)

1


In [59]:
# Use of around()
d = np.array([1.3467, 3.10987,4.91236])
print(d)
np.around(d,2)

[1.3467  3.10987 4.91236]


array([1.35, 3.11, 4.91])

In [19]:
d

array([1.3467 , 3.10987, 4.91236])

In [67]:
# Use of np.sqrt()
d = np.array([1.3467, 3.10987,4.912])
print(d)
print(np.around(np.sqrt(d),2))

[1.3467  3.10987 4.912  ]
[1.16 1.76 2.22]


#### 2D array

In [71]:
a1 = np.array([[3,4,5,8],[7,2,8, np.NAN]])
print(a1)
print(a1.shape)
print(a1.dtype)

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]
(2, 4)
float64


In [64]:
a1.reshape(4,2)
a1.dtype

(array([[ 3.,  4.],
        [ 5.,  8.],
        [ 7.,  2.],
        [ 8., nan]]),
 dtype('float64'))

In [33]:
# Create a 2d array
a1 = np.array([[3,4,5,8],[7,2,8,np.NaN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [35]:
# Use of  astype() to covert the data type
a1 = np.array([[3,4,5,8],[7,2,8,np.NaN]])
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [80]:
a1_copy3 = a1.astype(complex)
a1_copy3.dtype

dtype('complex128')

In [37]:
# Mathematical operations on rows and cols
a2 =np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [84]:
print(a2.sum(axis = 1))
print(a2.sum(axis=0))

[13 26 22]
[14 19 28]


In [79]:
# Find mean values along rows and cols
print(a2)
print(a2.mean(axis = 0))
print(a2.mean(axis = 1))

[[20 40]
 [30 60]]
[25. 50.]
[30. 45.]


In [86]:
np.sqrt(a2)

array([[1.73205081, 2.        , 2.44948974],
       [2.64575131, 3.        , 3.16227766],
       [2.        , 2.44948974, 3.46410162]])

In [90]:
# Matrix operations
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [5]:
# Matrix operations
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [98]:
# Define two matrices and multiply them
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = np.matmul(A, B)

print(C)

[[19 22]
 [43 50]]


In [104]:
# Print the Transpose of the matrices
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [1]:
# Accessing the array elements
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4

NameError: name 'np' is not defined

In [ ]:
# Slicing of array


In [3]:
a4[[0,3],[0,2]]

NameError: name 'a4' is not defined

In [ ]:
a4[3]

In [ ]:
a4[1]

In [ ]:
a4[1][2], a4[2][1]

In [ ]:
a4[1]

In [ ]:
for i in a4:
    print (i[1])

In [ ]:
[i[1] for i in a4]

In [ ]:
a4[:,2]

In [ ]:
a4[0][0],a4[0][2]

In [ ]:
a4[1:,2:]

In [110]:
# Accessing max value and its index
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [112]:
# Print the index position of max element
print(np.argmax(a3,axis=1))
print(np.argmax(a3,axis=0))

[2 2 0]
[2 0 1]


In [114]:
# Print the max value element+
print(np.amax(a3, axis =1))
print(np.amax(a3, axis =0))

[5 8 9]
[9 4 8]


#### ELEMENT-WISE Addition, subtraction etc

In [116]:
a1= np.array([1,2,3])
a2  = np.array([3,8,9])
a1+a2

array([ 4, 10, 12])

In [118]:
a1*a2

array([ 3, 16, 27])

In [120]:
a1/a2

array([0.33333333, 0.25      , 0.33333333])

In [122]:
b1 = np.array([[1,2],[4,8]])
b2 = np.array([[3,4],[1,1]])
b1*b2

array([[3, 8],
       [4, 8]])

In [1]:
import numpy as np
data = np.loadtxt('sensor_data.csv', delimiter=',')
normalized_data = (data - np.mean(data, axis=0)) / np.std(data, axis=0)


FileNotFoundError: sensor_data.csv not found.