In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt  
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, Lasso, ElasticNet

In [5]:
df = pd.read_csv("Cars.csv")
df

HP        MPG  VOL          SP         WT
0    49  53.700681   89  104.185353  28.762059
1    55  50.013401   92  105.461264  30.466833
2    55  50.013401   92  105.461264  30.193597
3    70  45.696322   92  113.461264  30.632114
4    53  50.504232   92  104.461264  29.889149
..  ...        ...  ...         ...        ...
76  322  36.900000   50  169.598513  16.132947
77  238  19.197888  115  150.576579  37.923113
78  263  34.000000   50  151.598513  15.769625
79  295  19.833733  119  167.944460  39.423099
80  236  12.101263  107  139.840817  34.948615

[81 rows x 5 columns]

In [7]:
# Features and target, consider all x columns
X = df.drop(columns=["MPG"])
y = df["MPG"]

In [13]:
# Train model on entire dataset
model1 = LinearRegression()
model1.fit(X, y)

LinearRegression()

In [15]:
y_pred = model1.predict(X)
y_pred

array([43.44193477, 42.38879289, 42.27934147, 42.53835981, 42.17264802,
       43.02061916, 42.32536062, 48.07621852, 48.28120247, 40.79122814,
       41.52153227, 47.80956747, 39.95980269, 41.52757889, 41.76632332,
       41.6181448 , 41.15094046, 47.98605515, 41.30861046, 37.87127922,
       38.57706414, 37.35199705, 37.89770285, 39.5625144 , 39.93380662,
       46.73870908, 35.48165898, 38.78152504, 38.24861192, 36.00285298,
       34.84603989, 37.21630246, 37.13919796, 34.82541399, 37.22361389,
       37.53950097, 39.27144845, 38.24219888, 38.54286458, 35.9391722 ,
       34.2129755 , 35.36313259, 37.50473376, 38.07998482, 35.79651664,
       36.2613377 , 34.21826465, 35.59393404, 36.91805291, 33.31108154,
       33.21313413, 33.3023649 , 29.19864884, 27.52358579, 28.3207133 ,
       28.56722621, 35.81583602, 33.02108459, 35.37334971, 32.29909503,
       29.87685849, 28.76093817, 25.14188416, 26.47040896, 25.97651933,
       36.35652478, 26.0975912 , 23.6416178 , 24.39887199, 20.21

In [25]:
from sklearn.metrics import mean_squared_error, \
                           mean_absolute_error, r2_score
print("MSE :",mean_squared_error(y_pred, y))
print("R2 :",r2_score(y_pred,y))

MSE : 18.897141152343107
R2 : 0.7022042487945386


In [29]:
# Print the model coefficients
print(model1.intercept_)
print(model1.coef_)

30.67733585215171
[-0.20544372 -0.33605084  0.39562692  0.40057409]


#### Ridge regularization

In [70]:
model2 = Ridge(alpha = 10)
model2.fit(X,y)

Ridge(alpha=10)

In [72]:
y_pred = model2.predict(X)
y_pred

array([43.54851706, 42.30069228, 42.26767499, 42.39509422, 42.24720751,
       42.88688399, 42.2815572 , 48.13787133, 48.19970711, 40.75558656,
       41.45692098, 47.88166556, 39.85728607, 41.45874502, 41.70894448,
       41.48606527, 41.22212641, 47.93490511, 41.26968938, 37.95422683,
       38.61716468, 37.42957444, 38.02660994, 39.4623629 , 40.02606677,
       46.73562642, 35.60553607, 38.67884267, 38.1752554 , 35.89251166,
       34.98397387, 37.1996704 , 37.25836393, 34.71339414, 37.35661978,
       37.60832416, 39.28515494, 38.31223439, 38.40293367, 35.93782657,
       34.15815622, 35.31317257, 37.39714821, 38.21060633, 35.91737324,
       36.22572307, 34.2241639 , 35.57436337, 36.92573855, 33.23381502,
       33.20426806, 33.23118555, 29.3382039 , 27.39003818, 28.29634739,
       28.6483431 , 35.82548973, 33.1463341 , 35.43769923, 32.36047435,
       29.77036931, 28.86586043, 25.10239712, 26.42665705, 25.90128595,
       36.45483419, 25.97214787, 23.73059565, 24.42077766, 20.11

In [74]:
print("MSE :",mean_squared_error(y_pred, y))
print("R2 :",r2_score(y_pred,y))

MSE : 18.90422935702324
R2 : 0.7017456648463373


In [76]:
# Print the model coefficients
print(model2.intercept_)
print(model2.coef_)

30.644008650931323
[-0.20500044 -0.24204108  0.39367954  0.1208378 ]


#### Lasso Regression

In [79]:
model3 = Lasso()
model3.fit(X,y)

Lasso()

In [81]:
y_pred = model3.predict(X)
y_pred

array([43.6371605 , 42.33851899, 42.33851899, 41.9003754 , 42.41532932,
       42.41685038, 42.33851899, 48.61066292, 48.61066292, 40.34440382,
       41.33609769, 47.45850798, 39.02275022, 41.33609769, 41.74286773,
       41.33609769, 40.93768911, 47.45850798, 40.93768911, 37.58332397,
       38.1951469 , 37.50917331, 37.59768088, 39.27201258, 39.66358076,
       46.63090467, 35.09629711, 38.1951469 , 38.87056189, 35.42988634,
       35.0924101 , 37.33046826, 37.05194082, 34.29740768, 37.58361764,
       37.61651226, 39.33809546, 38.39394682, 38.39394682, 35.45804896,
       34.15244217, 35.35755042, 37.36099688, 38.45640021, 36.12299404,
       36.23269896, 34.16679911, 35.62087603, 36.4909989 , 33.51916433,
       33.51916433, 33.51916433, 29.55952294, 26.61205273, 27.93189156,
       28.56964382, 36.48795679, 33.51916433, 35.99001951, 32.65056251,
       29.54195511, 29.50335874, 25.3252773 , 26.70254388, 26.11107334,
       37.06856726, 26.05043469, 23.8123765 , 24.5010098 , 19.46

In [83]:
print("MSE :",mean_squared_error(y_pred, y))
print("R2 :",r2_score(y_pred,y))

MSE : 19.07074802976587
R2 : 0.692301115588949


In [85]:
# Print the model coefficients
print(model3.intercept_)
print(model3.coef_)

41.11655857360363
[-0.17633905 -0.19752995  0.27586777 -0.        ]
